name: "Run locally"
on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "dist/index.js"
jobs:
  run:
    runs-on: ${{ matrix.os }}
    if: ${{ always() }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - macos-11
          - windows-2016
          - windows-2019
          - windows-2022
    steps:
      - uses: actions/checkout@v1
        if: github.repository == 'matootie/dokube'
      - uses: ./
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: matootie
          expirationTime: 90
          namespace: default
          version: 1.21.9
      - run: kubectl get nodes
      - run: kubectl top nodes
